version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias para lambda1"
      - pip install -r lambda1/requirements.txt -t lambda1/ || true
  build:
    commands:
      - echo "Listo para desplegar archivos de lambda1 sin comprimir"

artifacts:
  files:
    - lambda_function.py

