version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias para lambda1"
      - pip install -r lambda1/requirements.txt -t lambda1/ || true
      - echo "Instalando dependencias para lambda2"
      - pip install -r lambda2/requirements.txt -t lambda2/ || true
  build:
    commands:
      - echo "Empaquetando lambda1"
      - cd lambda1 && zip -r ../lambda1.zip . && cd ..
      - echo "Empaquetando lambda2"
      - cd lambda2 && zip -r ../lambda2.zip . && cd ..

artifacts:
  secondary-artifacts:
    lambda1artifact:
      files:
        - lambda1.zip
    lambda2artifact:
      files:
        - lambda2.zip
